// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: urls_table.sql

package urls_mapping

import (
	"context"
)

const deleteUrl = `-- name: DeleteUrl :exec
DELETE FROM url_mapping
WHERE long_url = $1
`

func (q *Queries) DeleteUrl(ctx context.Context, longUrl string) error {
	_, err := q.db.Exec(ctx, deleteUrl, longUrl)
	return err
}

const getUrl = `-- name: GetUrl :one
SELECT id, long_url, short_url, created_at FROM url_mapping
WHERE long_url = $1 LIMIT 1
`

func (q *Queries) GetUrl(ctx context.Context, longUrl string) (UrlMapping, error) {
	row := q.db.QueryRow(ctx, getUrl, longUrl)
	var i UrlMapping
	err := row.Scan(
		&i.ID,
		&i.LongUrl,
		&i.ShortUrl,
		&i.CreatedAt,
	)
	return i, err
}

const insertUrl = `-- name: InsertUrl :one
INSERT INTO url_mapping (long_url, short_url)
VALUES ($1, $2) RETURNING id, long_url, short_url, created_at
`

type InsertUrlParams struct {
	LongUrl  string
	ShortUrl string
}

func (q *Queries) InsertUrl(ctx context.Context, arg InsertUrlParams) (UrlMapping, error) {
	row := q.db.QueryRow(ctx, insertUrl, arg.LongUrl, arg.ShortUrl)
	var i UrlMapping
	err := row.Scan(
		&i.ID,
		&i.LongUrl,
		&i.ShortUrl,
		&i.CreatedAt,
	)
	return i, err
}

const updateUrl = `-- name: UpdateUrl :one
UPDATE url_mapping SET short_url = $1
WHERE long_url = $2 RETURNING id, long_url, short_url, created_at
`

type UpdateUrlParams struct {
	ShortUrl string
	LongUrl  string
}

func (q *Queries) UpdateUrl(ctx context.Context, arg UpdateUrlParams) (UrlMapping, error) {
	row := q.db.QueryRow(ctx, updateUrl, arg.ShortUrl, arg.LongUrl)
	var i UrlMapping
	err := row.Scan(
		&i.ID,
		&i.LongUrl,
		&i.ShortUrl,
		&i.CreatedAt,
	)
	return i, err
}
